swagger: '2.0'
info:
  description: API for getting BTC info for Atlas
  version: 1.0.0
  title: Atlas BTC API
  # put the contact info for your development or API team
  contact:
    email: brian@blockdynamics.io
paths:
  /price:
    get:
      description: get the current price of btc
      responses:
        200:
          description: get price success
          schema:
            type: integer
        400:
          description: get price failed
          
  /volume:
    get:
      description: get the volume in 24hr of btc
      responses:
        200:
          description: get volume success
          schema:
            type: integer
        400:
          description: get volume failed
          
  /supply:
    get:
      description: get the current circulating supply of btc
      responses:
        200:
          description: get supply success
          schema:
            type: integer
        400:
          description: get supply failed
          
  /MaxSupply:
    get:
      description: get the maximum supply of btc
      responses:
        200:
          description: get supply success
          schema:
            type: integer
        400:
          description: get supply failed
          
  /blockSize:
    get:
      description: get the average block size of btc
      responses:
        200:
          description: get size success
          schema:
            type: integer
        400:
          description: get size failed

  /outputList:
    get:
      description: get the income source distribution of certain wallet
      parameters:
        - name: address
          in: query
          description: the address of the wallet to be queried
          type: string
          
        - name: hash
          in: query
          description: the hash of the wallet to be queried
          type: string
          
        - name: timestamp
          in: query
          description: the timestamp of request
          type: string
          
        - name: status
          in: query
          description: the status of the request
          type: string
          
      responses:
        200:
          description: query data success
          schema:
            type: object
            properties:
              hash:
                type: string
              address:
                type: string
              timestamp:
                type: string
              status:
                type: string
              total:
                type: integer
              distribution:
                type: array
                items: 
                  type: integer
              
        400:
          description: input error
          
        404:
          description: address not found
          
